export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const CHANGE_MENU = "CHANGE_MENU";
export const GET_MENUS_SUCCESS = "GET_MENUS_SUCCESS";
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
export const CHANGE_SERVICE = "CHANGE_SERVICE";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";